spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false

notification:
  webhook:
    url: http://webhook-mock:9999
