spring:
  application:
    name: transaction-service
  config:
    import: "optional:configserver:http://config-server:9191"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka-broker:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity-service:8081 # Use service name for Docker

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      kafkaPublisher:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 5000
        failureRateThreshold: 50

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
