spring:
  application:
    name: transaction-service
  config:
    import: "optional:configserver:http://config-server:9191"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt: {}

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      snsPublisher:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 5000
        failureRateThreshold: 50

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
