server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 100
            redis-rate-limiter.burstCapacity: 100
            redis-rate-limiter.requestedTokens: 1
            key-resolver: "#{@userKeyResolver}"
      routes:
        - id: discovery-server
          uri: lb://discovery-server
          predicates:
            - Path=/api/v1/discovery/**
        - id: config-server
          uri: lb://config-server
          predicates:
            - Path=/api/v1/config/**
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/v1/identity/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/v1/transactions/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/api/v1/audit/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
