spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:http://localhost:8888"
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Mock webhook URL to simulate sending emails/SMS
notification:
  webhook:
    url: http://localhost:9999
