server:
  port: 9191

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pramodkolte/my_bank_config.git
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
